-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v2 by xnovaks1@stuba.sk ***



-- ************************************** "Register options"

CREATE TABLE "Register options"
(
 "pk id"    int NOT NULL,
 platform text NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( "pk id" )
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v2 by xnovaks1@stuba.sk ***



-- ************************************** "User"

CREATE TABLE "User"
(
 "pk id"             int NOT NULL,
 email             text NOT NULL,
 registered_trough int NOT NULL,
 username          text NOT NULL,
 CONSTRAINT PK_20 PRIMARY KEY ( "pk id" ),
 CONSTRAINT FK_24 FOREIGN KEY ( registered_trough ) REFERENCES "Register options" ( "pk id" )
);

CREATE INDEX FK_26 ON "User"
(
 registered_trough
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Causes of death"

CREATE TABLE "Causes of death"
(
 "id"          int NOT NULL,
 title       text NOT NULL,
 description text NOT NULL,
 CONSTRAINT PK_318 PRIMARY KEY ( "id" )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Character hits"

CREATE TABLE "Character hits"
(
 "id"                 int NOT NULL,
 direction_of_atack boolean NOT NULL,
 character1_id      int NOT NULL,
 character2_id      int NOT NULL,
 damage             decimal NOT NULL,
 CONSTRAINT PK_194 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_197 FOREIGN KEY ( character2_id ) REFERENCES "Users characters" ( "id" ),
 CONSTRAINT FK_200 FOREIGN KEY ( character1_id ) REFERENCES "Users characters" ( "id" )
);

CREATE INDEX FK_199 ON "Character hits"
(
 character2_id
);

CREATE INDEX FK_202 ON "Character hits"
(
 character1_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Character items"

CREATE TABLE "Character items"
(
 "id"           int NOT NULL,
 character_id int NOT NULL,
 item_id      int NOT NULL,
 CONSTRAINT PK_205 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_206 FOREIGN KEY ( character_id ) REFERENCES "Users characters" ( "id" ),
 CONSTRAINT FK_220 FOREIGN KEY ( item_id ) REFERENCES Items ( "id" )
);

CREATE INDEX FK_208 ON "Character items"
(
 character_id
);

CREATE INDEX FK_222 ON "Character items"
(
 item_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Character skills"

CREATE TABLE "Character skills"
(
 "id"           int NOT NULL,
 skill_id     int NOT NULL,
 character_id int NOT NULL,
 CONSTRAINT PK_185 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_186 FOREIGN KEY ( skill_id ) REFERENCES Skills ( "id" ),
 CONSTRAINT FK_189 FOREIGN KEY ( character_id ) REFERENCES "Users characters" ( "id" )
);

CREATE INDEX FK_188 ON "Character skills"
(
 skill_id
);

CREATE INDEX FK_191 ON "Character skills"
(
 character_id
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Characters"

CREATE TABLE "Characters"
(
 "id"            int NOT NULL,
 hp            decimal NOT NULL,
 attack_damage decimal NOT NULL,
 shield        decimal NOT NULL,
 name          text NOT NULL,
 description   text NOT NULL,
 CONSTRAINT PK_134 PRIMARY KEY ( "id" )
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Completed user quests"

CREATE TABLE "Completed user quests"
(
 "id"            int NOT NULL,
 user_id       int NOT NULL,
 user_quest_id int NOT NULL,
 CONSTRAINT PK_102 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_103 FOREIGN KEY ( user_id ) REFERENCES "User" ( "pk id" ),
 CONSTRAINT FK_115 FOREIGN KEY ( user_quest_id ) REFERENCES "User quests" ( "id" )
);

CREATE INDEX FK_105 ON "Completed user quests"
(
 user_id
);

CREATE INDEX FK_117 ON "Completed user quests"
(
 user_quest_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Completed_floor_quests

CREATE TABLE Completed_floor_quests
(
 "id"             int NOT NULL,
 floor_quest_id int NOT NULL,
 character_id   int NOT NULL,
 CONSTRAINT PK_287 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_288 FOREIGN KEY ( floor_quest_id ) REFERENCES "Floor quests" ( "id" ),
 CONSTRAINT FK_291 FOREIGN KEY ( character_id ) REFERENCES "Users characters" ( "id" )
);

CREATE INDEX FK_290 ON Completed_floor_quests
(
 floor_quest_id
);

CREATE INDEX FK_293 ON Completed_floor_quests
(
 character_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Floor quests"

CREATE TABLE "Floor quests"
(
 "id"                       int NOT NULL,
 required_monsters_killed int NOT NULL,
 item_drop                int NOT NULL,
 floor_id                 int NOT NULL,
 required_character_level int NOT NULL,
 name                     text NOT NULL,
 description              text NOT NULL,
 xp_drop                  decimal NOT NULL,
 CONSTRAINT PK_273 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_279 FOREIGN KEY ( floor_id ) REFERENCES Floors ( "id" ),
 CONSTRAINT FK_282 FOREIGN KEY ( item_drop ) REFERENCES Items ( "id" )
);

CREATE INDEX FK_281 ON "Floor quests"
(
 floor_id
);

CREATE INDEX FK_284 ON "Floor quests"
(
 item_drop
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Floors

CREATE TABLE Floors
(
 "id"                       int NOT NULL,
 floor_number             int NOT NULL,
 character_level_required int NOT NULL,
 CONSTRAINT PK_265 PRIMARY KEY ( "id" )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Floors in maps"

CREATE TABLE "Floors in maps"
(
 "id"       int NOT NULL,
 lenght   int NOT NULL,
 floor_id int NOT NULL,
 map_id   int NOT NULL,
 width    int NOT NULL,
 CONSTRAINT PK_233 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_260 FOREIGN KEY ( map_id ) REFERENCES "Map" ( "id" ),
 CONSTRAINT FK_268 FOREIGN KEY ( floor_id ) REFERENCES Floors ( "id" )
);

CREATE INDEX FK_262 ON "Floors in maps"
(
 map_id
);

CREATE INDEX FK_270 ON "Floors in maps"
(
 floor_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Friends

CREATE TABLE Friends
(
 "id"        NOT NULL,
 user1_id int NOT NULL,
 user2_id int NOT NULL,
 CONSTRAINT PK_44 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_45 FOREIGN KEY ( user1_id ) REFERENCES "User" ( "pk id" ),
 CONSTRAINT FK_48 FOREIGN KEY ( user2_id ) REFERENCES "User" ( "pk id" )
);

CREATE INDEX FK_47 ON Friends
(
 user1_id
);

CREATE INDEX FK_50 ON Friends
(
 user2_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Items

CREATE TABLE Items
(
 "id"          int NOT NULL,
 name        text NOT NULL,
 description text NOT NULL,
 hp_buff     decimal NOT NULL,
 ad_buff     decimal NOT NULL,
 shield_buff decimal NOT NULL,
 CONSTRAINT PK_211 PRIMARY KEY ( "id" )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Items on floors"

CREATE TABLE "Items on floors"
(
 "id"           int NOT NULL,
 floor_x      int NOT NULL,
 map_floor_id int NOT NULL,
 item_id      int NOT NULL,
 floor_y      int NOT NULL,
 CONSTRAINT PK_225 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_228 FOREIGN KEY ( item_id ) REFERENCES Items ( "id" ),
 CONSTRAINT FK_237 FOREIGN KEY ( map_floor_id ) REFERENCES "Floors in maps" ( "id" )
);

CREATE INDEX FK_230 ON "Items on floors"
(
 item_id
);

CREATE INDEX FK_239 ON "Items on floors"
(
 map_floor_id
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Local users"

CREATE TABLE "Local users"
(
 "id"         int NOT NULL,
 password   text NOT NULL,
 "pk user_id" int NOT NULL,
 CONSTRAINT PK_29 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_39 FOREIGN KEY ( "pk user_id" ) REFERENCES "User" ( "pk id" )
);

CREATE INDEX FK_41 ON "Local users"
(
 "pk user_id"
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Map"

CREATE TABLE "Map"
(
 "id"          int NOT NULL,
 name        text NOT NULL,
 description text NOT NULL,
 CONSTRAINT PK_257 PRIMARY KEY ( "id" )
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Messages

CREATE TABLE Messages
(
 "id"             int NOT NULL,
 direction_1to2 boolean NOT NULL,
 friends_id      NOT NULL,
 "date"           timestamp NOT NULL,
 CONSTRAINT PK_53 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_56 FOREIGN KEY ( friends_id ) REFERENCES Friends ( "id" )
);

CREATE INDEX FK_58 ON Messages
(
 friends_id
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Monster killed"

CREATE TABLE "Monster killed"
(
 "id"           int NOT NULL,
 character_id int NOT NULL,
 CONSTRAINT PK_245 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_249 FOREIGN KEY ( character_id ) REFERENCES "Users characters" ( "id" )
);

CREATE INDEX FK_251 ON "Monster killed"
(
 character_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Monster_hits

CREATE TABLE Monster_hits
(
 "id"                  int NOT NULL,
 direction_of_attack boolean NOT NULL,
 character_id        int NOT NULL,
 monster_id          int NOT NULL,
 damage              decimal NOT NULL,
 CONSTRAINT PK_307 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_310 FOREIGN KEY ( monster_id ) REFERENCES "Monsters on floors" ( "id" ),
 CONSTRAINT FK_313 FOREIGN KEY ( character_id ) REFERENCES "Users characters" ( "id" )
);

CREATE INDEX FK_312 ON Monster_hits
(
 monster_id
);

CREATE INDEX FK_315 ON Monster_hits
(
 character_id
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Monsters

CREATE TABLE Monsters
(
 "id"                  int NOT NULL,
 name                text NOT NULL,
 description         text NOT NULL,
 hp                  decimal NOT NULL,
 attack_damge        decimal NOT NULL,
 shield              decimal NOT NULL,
 user_level_required int NOT NULL,
 xp_drop             decimal NOT NULL,
 CONSTRAINT PK_329 PRIMARY KEY ( "id" )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Monsters items"

CREATE TABLE "Monsters items"
(
 "id"         int NOT NULL,
 monster_id int NOT NULL,
 item_id    int NOT NULL,
 CONSTRAINT PK_342 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_343 FOREIGN KEY ( monster_id ) REFERENCES "Monsters on floors" ( "id" ),
 CONSTRAINT FK_346 FOREIGN KEY ( item_id ) REFERENCES Items ( "id" )
);

CREATE INDEX FK_345 ON "Monsters items"
(
 monster_id
);

CREATE INDEX FK_348 ON "Monsters items"
(
 item_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Monsters on floors"

CREATE TABLE "Monsters on floors"
(
 "id"             int NOT NULL,
 actual_hp      decimal NOT NULL,
 monster_id     int NOT NULL,
 cause_of_death int NOT NULL,
 floor_id       int NOT NULL,
 floor_x        int NOT NULL,
 floor_y        int NOT NULL,
 rotation       int NOT NULL,
 dead           boolean NOT NULL,
 CONSTRAINT PK_296 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_302 FOREIGN KEY ( floor_id ) REFERENCES "Floors in maps" ( "id" ),
 CONSTRAINT FK_321 FOREIGN KEY ( cause_of_death ) REFERENCES "Causes of death" ( "id" ),
 CONSTRAINT FK_337 FOREIGN KEY ( monster_id ) REFERENCES Monsters ( "id" )
);

CREATE INDEX FK_304 ON "Monsters on floors"
(
 floor_id
);

CREATE INDEX FK_323 ON "Monsters on floors"
(
 cause_of_death
);

CREATE INDEX FK_339 ON "Monsters on floors"
(
 monster_id
);
-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Register options"

CREATE TABLE "Register options"
(
 "pk id"    int NOT NULL,
 platform text NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( "pk id" )
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Roles

CREATE TABLE Roles
(
 "id"               int NOT NULL,
 hp_per_level     decimal NOT NULL,
 ad_per_level     decimal NOT NULL,
 shield_per_level decimal NOT NULL,
 name             text NOT NULL,
 CONSTRAINT PK_143 PRIMARY KEY ( "id" )
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Roles xp requirements"

CREATE TABLE "Roles xp requirements"
(
 "id"          int NOT NULL,
 level       int NOT NULL,
 role_id     int NOT NULL,
 xp_required decimal NOT NULL,
 CONSTRAINT PK_155 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_161 FOREIGN KEY ( role_id ) REFERENCES Roles ( "id" )
);

CREATE INDEX FK_163 ON "Roles xp requirements"
(
 role_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Skill tree"

CREATE TABLE "Skill tree"
(
 "id"             int NOT NULL,
 skill_id       int NOT NULL,
 required_skill int NOT NULL,
 CONSTRAINT PK_176 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_177 FOREIGN KEY ( skill_id ) REFERENCES Skills ( "id" ),
 CONSTRAINT FK_180 FOREIGN KEY ( required_skill ) REFERENCES Skills ( "id" )
);

CREATE INDEX FK_179 ON "Skill tree"
(
 skill_id
);

CREATE INDEX FK_182 ON "Skill tree"
(
 required_skill
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Skills

CREATE TABLE Skills
(
 "id"                  int NOT NULL,
 character_level_min int NOT NULL,
 role_id             int NOT NULL,
 extra_damage        decimal NOT NULL,
 name                text NOT NULL,
 description         text NOT NULL,
 CONSTRAINT PK_166 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_171 FOREIGN KEY ( role_id ) REFERENCES Roles ( "id" )
);

CREATE INDEX FK_173 ON Skills
(
 role_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Team invitations"

CREATE TABLE "Team invitations"
(
 "id"           int NOT NULL,
 accepted      NOT NULL,
 team_id      int NOT NULL,
 invited_user int NOT NULL,
 CONSTRAINT PK_79 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_81 FOREIGN KEY ( invited_user ) REFERENCES "User" ( "pk id" ),
 CONSTRAINT FK_84 FOREIGN KEY ( team_id ) REFERENCES Teams ( "id" )
);

CREATE INDEX FK_83 ON "Team invitations"
(
 invited_user
);

CREATE INDEX FK_86 ON "Team invitations"
(
 team_id
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Team members"

CREATE TABLE "Team members"
(
 "id"            int NOT NULL,
 is_member_now boolean NOT NULL,
 team_id       int NOT NULL,
 user_id       int NOT NULL,
 CONSTRAINT PK_61 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_63 FOREIGN KEY ( user_id ) REFERENCES "User" ( "pk id" ),
 CONSTRAINT FK_71 FOREIGN KEY ( team_id ) REFERENCES Teams ( "id" )
);

CREATE INDEX FK_65 ON "Team members"
(
 user_id
);

CREATE INDEX FK_73 ON "Team members"
(
 team_id
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Team messages"

CREATE TABLE "Team messages"
(
 "id"           int NOT NULL,
 requirements text NOT NULL,
 author       int NOT NULL,
 team_id      int NOT NULL,
 message      text NOT NULL,
 "date"         timestamp NOT NULL,
 CONSTRAINT PK_89 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_94 FOREIGN KEY ( team_id ) REFERENCES Teams ( "id" ),
 CONSTRAINT FK_97 FOREIGN KEY ( author ) REFERENCES "User" ( "pk id" )
);

CREATE INDEX FK_96 ON "Team messages"
(
 team_id
);

CREATE INDEX FK_99 ON "Team messages"
(
 author
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** Teams

CREATE TABLE Teams
(
 "id"            int NOT NULL,
 name          text NOT NULL,
 owner_id      int NOT NULL,
 members_count int NOT NULL,
 CONSTRAINT PK_68 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_74 FOREIGN KEY ( owner_id ) REFERENCES "User" ( "pk id" )
);

CREATE INDEX FK_76 ON Teams
(
 owner_id
);

-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "User"

CREATE TABLE "User"
(
 "pk id"             int NOT NULL,
 email             text NOT NULL,
 registered_trough int NOT NULL,
 username          text NOT NULL,
 CONSTRAINT PK_20 PRIMARY KEY ( "pk id" ),
 CONSTRAINT FK_24 FOREIGN KEY ( registered_trough ) REFERENCES "Register options" ( "pk id" )
);

CREATE INDEX FK_26 ON "User"
(
 registered_trough
);


-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "User quests"

CREATE TABLE "User quests"
(
 "id"           int NOT NULL,
 requirements text NOT NULL,
 name         text NOT NULL,
 description  text NOT NULL,
 CONSTRAINT PK_108 PRIMARY KEY ( "id" )
);



-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Untitled Project, v4 by xnovaks1@stuba.sk ***



-- ************************************** "Users characters"

CREATE TABLE "Users characters"
(
 "id"              int NOT NULL,
 character_level int NOT NULL,
 cause_of_death  int NULL,
 floor_id        int NOT NULL,
 role_id         int NOT NULL,
 character_id    int NOT NULL,
 user_id         int NOT NULL,
 hp              decimal NOT NULL,
 attack_damage   decimal NOT NULL,
 shield          decimal NOT NULL,
 "exp"             decimal NOT NULL,
 floor_x         int NOT NULL,
 floor_y         int NOT NULL,
 rotation         NOT NULL,
 CONSTRAINT PK_120 PRIMARY KEY ( "id" ),
 CONSTRAINT FK_129 FOREIGN KEY ( user_id ) REFERENCES "User" ( "pk id" ),
 CONSTRAINT FK_138 FOREIGN KEY ( character_id ) REFERENCES "Characters" ( "id" ),
 CONSTRAINT FK_147 FOREIGN KEY ( role_id ) REFERENCES Roles ( "id" ),
 CONSTRAINT FK_240 FOREIGN KEY ( floor_id ) REFERENCES "Floors in maps" ( "id" ),
 CONSTRAINT FK_324 FOREIGN KEY ( cause_of_death ) REFERENCES "Causes of death" ( "id" )
);

CREATE INDEX FK_131 ON "Users characters"
(
 user_id
);

CREATE INDEX FK_140 ON "Users characters"
(
 character_id
);

CREATE INDEX FK_149 ON "Users characters"
(
 role_id
);

CREATE INDEX FK_242 ON "Users characters"
(
 floor_id
);

CREATE INDEX FK_326 ON "Users characters"
(
 cause_of_death
);


















































































































































































